---
- name: "Get latest Docker image: {{ wtd_docker_collabora_image }}"
  docker_image:
    name: "{{ wtd_docker_collabora_image }}"

- name: Start container
  docker_container:
    name: "{{ wtd_docker_collabora_name }}"
    image: "{{ wtd_docker_collabora_image }}"
    state: started
    ports:
      - "{{ wtd_docker_collabora_ports }}"
    env:
      domain: "{{ wtd_docker_collabora_domains }}"
    capabilities:
      - "{{ wtd_docker_collabora_capabilities }}"
